# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-25 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        ('sign', '0002_sign_sing_akp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('apk_name', models.CharField(max_length=200, null=True, verbose_name='包名')),
                ('app_name', models.CharField(max_length=200, null=True, verbose_name='应用名')),
                ('Edition', models.CharField(help_text='版本号不能重复填写', max_length=200, null=True, unique=True, verbose_name='版本号')),
                ('apk_file', models.FileField(null=True, upload_to='apk/%Y/%m/%d/', verbose_name='APK包')),
                ('cpUser', models.CharField(blank=True, max_length=100, null=True, verbose_name='开发者')),
                ('isdelete', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.Channel', verbose_name='渠道')),
                ('sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sign.Sign', verbose_name='签名')),
            ],
            options={
                'verbose_name': '生成签名',
                'verbose_name_plural': '生成签名',
                'db_table': 'apk',
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(blank=True, help_text='请输入6位以上', max_length=100, null=True)),
                ('Alias', models.CharField(blank=True, help_text='必填项', max_length=100, null=True, unique=True)),
                ('Confirm', models.CharField(blank=True, help_text='必填项', max_length=100, null=True)),
                ('First_and_LastName', models.CharField(blank=True, help_text='必填项', max_length=100, null=True)),
                ('OrganizationalUnit', models.CharField(blank=True, help_text='必填项', max_length=100, null=True)),
                ('Organization', models.CharField(blank=True, help_text='必填项', max_length=100, null=True)),
                ('City_or_Locality', models.CharField(blank=True, help_text='必填项', max_length=100, null=True)),
                ('State_or_Province', models.CharField(blank=True, help_text='必填项', max_length=100, null=True)),
                ('Country_Code', models.CharField(blank=True, help_text='必填项', max_length=100, null=True)),
                ('channel', models.ForeignKey(help_text='必填项', null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.Channel', verbose_name='渠道')),
                ('sign', models.ForeignKey(blank=True, help_text='如果选择了签名，就不能再给当包新增签名', null=True, on_delete=django.db.models.deletion.CASCADE, to='sign.Sign', verbose_name='签名')),
            ],
            options={
                'verbose_name': '临时表',
                'verbose_name_plural': '临时表',
                'db_table': 'Temp',
            },
        ),
        migrations.CreateModel(
            name='CpApk',
            fields=[
            ],
            options={
                'verbose_name': '添加apk',
                'verbose_name_plural': '添加apk',
                'proxy': True,
            },
            bases=('apk.apk',),
        ),
    ]
