# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-25 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='Edition',
            field=models.CharField(help_text='同一个apk包版本号不能重复填写', max_length=200, null=True, verbose_name='版本号'),
        ),
    ]
