# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-23 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='签名码')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='签名文件')),
            ],
            options={
                'verbose_name': '签名',
                'verbose_name_plural': '签名',
                'db_table': 'sign',
            },
        ),
    ]
