# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='sing_akp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='带签名的apk'),
        ),
    ]
