# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-25 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelName', models.CharField(blank=True, max_length=100, null=True, verbose_name='渠道名')),
                ('channelNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='渠道号')),
                ('comName', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司名')),
                ('isdelete', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '渠道',
                'verbose_name_plural': '渠道',
                'db_table': 'channel',
            },
        ),
    ]
